// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowProgressNotification = { threadId: string, turnId: string, runId: string, cellId: string, event: string, unixMs: bigint, sessionId?: string | null, workflowToolCallId?: string | null, cwd?: string | null, gitBranch?: string | null, workflow?: string | null, phase?: string | null, agent?: string | null, agentId?: string | null, child?: string | null, childIndex?: bigint | null, childRunId?: string | null, itemIndex?: bigint | null, stageIndex?: bigint | null, stepIndex?: bigint | null, error?: string | null, message?: string | null, };
